heat_template_version: 2017-02-24

description: Creation of the admin Server.


###################################################################################
############################ Seccion de Parametros ################################
###################################################################################

parameters:

  server_name:
    type: string
    label: Server Name
    description: Name of the admin server of the scenario.

  key_name:
    type: string
    label: KeyPair Name
    description: Name of the keypair for the admin server of the scenario.

  securityGroup:
    type: string
    label: SecurityGroup Name
    description: Name of the security group to associate to the admin server of the scenario.

  net:
    type: string
    label: Network ID
    description: ID of the Network in which the admin server will be connected to.

  subnet:
    type: string
    label: Subnet ID
    description: ID of the Sub-Network in which the admin server will be connected to.


###################################################################################
###################################################################################
###################################################################################



###################################################################################
############################# Seccion de Recursos #################################
###################################################################################

resources:

  keypair:
    type: OS::Nova::KeyPair
    properties:
      save_private_key: true
      name: { get_param: key_name }

  admin_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        runcmd:
          - sed -i 's/Port 22/Port 6666/g' /etc/ssh/sshd_config
          - service ssh restart

  admin_vm_port:
    type: OS::Neutron::Port
    properties:
      security_groups: [ { get_param: securityGroup } ]
      network_id: { get_param: net }
      fixed_ips:
        - subnet_id: { get_param: subnet }

  admin_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: ExtNet
      port_id: { get_resource: admin_vm_port }

  admin_vm:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      key_name: { get_resource: keypair }
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      user_data_format: SOFTWARE_CONFIG
      user_data: { get_resource: admin_config }
      networks: 
        - port: { get_resource: admin_vm_port }


###################################################################################
###################################################################################
###################################################################################



###################################################################################
############################# Seccion de Salidas ##################################
###################################################################################

outputs:

  Admin_FloatingIP_Address:
    description: The FloatingIP_Address of the admin server.
    value: { get_resource: admin_floating_ip }


###################################################################################
###################################################################################
###################################################################################