heat_template_version: 2017-02-24

description: Creation of the DataBase Server.


###################################################################################
############################ Seccion de Parametros ################################
###################################################################################

parameters:

  server_name:
    type: string
    label: Server Name
    description: Name of the admin server of the scenario.

  key_name:
    type: string
    label: KeyPair Name
    description: Name of the keypair for the admin server of the scenario.

  securityGroup:
    type: string
    label: SecurityGroup Name
    description: Name of the security group to associate to the admin server of the scenario.

  net:
    type: string
    label: Network ID
    description: ID of the Network in which the admin server will be connected to.

  subnet:
    type: string
    label: Subnet ID
    description: ID of the Sub-Network in which the admin server will be connected to.

  fixed_ip_address:
    type: string
    label: Fixed IP Address
    description: Fixed IP Address for zookeeper server of the zookeeper ensemble.


###################################################################################
###################################################################################
###################################################################################



###################################################################################
############################# Seccion de Recursos #################################
###################################################################################

resources:

  keypair:
    type: OS::Nova::KeyPair
    properties:
      save_private_key: true
      name: { get_param: key_name }

  bbdd_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        runcmd:
          - apt-get update
          - echo mysql-server mysql-server/root_password select 1234 | debconf-set-selections
          - echo mysql-server mysql-server/root_password_again select 1234 | debconf-set-selections
          - apt-get -y install mysql-server
          - echo "Todo hecho" > /Final.txt

  bbdd_port:
    type: OS::Neutron::Port
    properties:
      security_groups: [ { get_param: securityGroup } ]
      network_id: { get_param: net }
      fixed_ips: [ { "subnet": { get_param: subnet }, "ip_address": { get_param: fixed_ip_address } } ]

  DataBase:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      key_name: { get_resource: keypair }
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      user_data_format: SOFTWARE_CONFIG
      user_data: { get_resource: bbdd_config }
      networks:
        - port: { get_resource: bbdd_port }


###################################################################################
###################################################################################
###################################################################################



###################################################################################
############################# Seccion de Salidas ##################################
###################################################################################

outputs:

  Server_IP:
    description: The IP address of the Zookeeper Server created.
    value: { get_attr: [DataBase, first_address] }


###################################################################################
###################################################################################
###################################################################################